target "SQKDataKit" do
    pod 'SQKDataKit/Core', :path => '../SQKDataKit.podspec'
    pod 'SQKDataKit/NSManagedObject+SQKAdditions', :path => '../SQKDataKit.podspec'
    pod 'SQKDataKit/SQKManagedObjectController', :path => '../SQKDataKit.podspec'
    pod 'SQKDataKit/SQKFetchedTableViewController', :path => '../SQKDataKit.podspec'
end

target "SQKDataKitTests" do
	pod 'OCMock', '~> 2.2.1'
    pod 'AGAsyncTestHelper', '~> 1.0'
end

