source 'https://github.com/CocoaPods/Specs.git'

target "SQKCoreDataOperation Example" do
	pod 'SQKDataKit/ContextManager', :path => '../../SQKDataKit.podspec'
	pod 'SQKDataKit/CoreDataOperation', :path => '../../SQKDataKit.podspec'
end

target "SQKCoreDataOperation ExampleTests" do
	pod 'SQKDataKit/ContextManager', :path => '../../SQKDataKit.podspec'
	pod 'SQKDataKit/CoreDataOperation', :path => '../../SQKDataKit.podspec'
  pod 'AGAsyncTestHelper', '~> 1.0'
	pod 'OCMock', '~> 3.1'
end
