link_with "SQKCoreDataOperation Example", "SQKCoreDataOperation ExampleTests"

pod 'SQKDataKit/Core', :path => '../../SQKDataKit.podspec'
pod 'SQKDataKit/CoreDataOperation', :path => '../../SQKDataKit.podspec'

